"""empty message

Revision ID: 632ae6c80c5d
Revises: 01e84607bf48
Create Date: 2020-04-03 17:18:46.909646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632ae6c80c5d'
down_revision = '01e84607bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_content'), 'todos', ['content'], unique=False)
    op.create_index(op.f('ix_todos_name'), 'todos', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_name'), table_name='todos')
    op.drop_index(op.f('ix_todos_content'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
